import { existsSync } from 'node:fs';
import { isAbsolute, join, resolve } from 'node:path';
import { isCancel, select } from '@clack/prompts';
import type { Command } from 'commander';
import { brand } from '../brand/colors.js';
import { sym } from '../brand/glyphs.js';
import { type Lockfile, type SourceSpec, readLockfileUpward } from '../core/lockfile/index.js';
import { loadFromPath } from '../core/sources/file-source.js';
import { BASELINE_REL_PATH, materializeBaseline } from '../core/upgrade/baseline.js';
import type { OrphanDecision } from '../core/upgrade/merge.js';
import { reconstructPristine } from '../core/upgrade/pristine.js';
import {
  type UpgradeEnvironment,
  UpgradeError,
  abortUpgrade,
  continueUpgrade,
  runUpgrade,
} from '../core/upgrade/run.js';

/**
 * `hex upgrade` (M11.5) — the CLI surface for the upgrade engine.
 *
 *   hex upgrade <new-template>   upgrade to the version at <new-template>
 *   hex upgrade --continue       finish a paused upgrade once conflicts are resolved
 *   hex upgrade --abort          discard a paused upgrade, rolling the tree back
 *
 * The plain form reconstructs `pristine_old` from the lockfile and
 * renders `pristine_new` from the supplied newer template, then 3-way
 * merges. A clean merge rewrites the lockfile and exits 0; a conflicting
 * one leaves marker-laden files, persists `.hex/upgrade-state.yaml`, and
 * exits non-zero.
 */
export function registerUpgrade(program: Command): void {
  program
    .command('upgrade')
    .description('upgrade a generated app to a newer template version')
    .argument('[template]', 'path to the newer version of the template')
    .option('--continue', 'resume a paused upgrade after resolving conflicts', false)
    .option('--abort', 'discard an in-progress upgrade, rolling the tree back', false)
    .option('--prompt-on-orphans', 'interactively triage orphaned files (kept by default)', false)
    .action(
      async (
        templateArg: string | undefined,
        opts: { continue: boolean; abort: boolean; promptOnOrphans: boolean },
      ) => {
        try {
          if (opts.continue && opts.abort) {
            throw new UpgradeError('pass either --continue or --abort, not both');
          }
          if (opts.abort) {
            const { from, to } = await abortUpgrade(process.cwd());
            console.log(
              brand.done(`${sym.ok()} upgrade ${from} → ${to} aborted — working tree rolled back`),
            );
            return;
          }
          if (opts.continue) {
            const { from, to } = await continueUpgrade(process.cwd());
            console.log(brand.done(`${sym.ok()} upgrade ${from} → ${to} complete`));
            return;
          }
          if (!templateArg) {
            throw new UpgradeError(
              'provide the path to the newer template, or pass --continue / --abort',
            );
          }
          await runPlainUpgrade(templateArg, opts.promptOnOrphans);
        } catch (err) {
          if (err instanceof UpgradeError) {
            console.error(brand.error(`${sym.err()} ${err.message}`));
            process.exitCode = 1;
            return;
          }
          throw err;
        }
      },
    );
}

/**
 * Guard the pre-baseline fallback. An app generated before Hex stored
 * `.hex/pristine/` can only get its merge base by re-rendering the
 * template recorded in the lockfile — which is sound *only* if that
 * template still holds the locked version. When it does not (the usual
 * case: the template was updated in place), re-rendering yields a tree
 * that merely impersonates the old version, and the 3-way merge quietly
 * throws the template's changes away. Refuse instead.
 *
 * `git:` sources pin a ref and `catalogue:` sources pin a version, so
 * their reconstruction is faithful and needs no guard.
 */
async function assertSourceStillHolds(lockfile: Lockfile, from: string): Promise<void> {
  const source = lockfile.root.source;
  if (source.kind !== 'file') return;

  const advice = [
    `Put a copy of the template at ${from} somewhere (e.g. \`git worktree add`,
    `../template-${from} v${from}\`), point \`root.source.path\` in .hex/lockfile.yaml at it,`,
    `and re-run. Hex records a reusable baseline (${BASELINE_REL_PATH}) as it upgrades, so this`,
    'is a one-off for apps generated by an older Hex.',
  ].join(' ');

  let actual: string;
  try {
    actual = (await loadFromPath(source.path)).manifest.version;
  } catch {
    throw new UpgradeError(
      `cannot rebuild the ${from} baseline — no template found at ${source.path}, and this app carries no ${BASELINE_REL_PATH}.\n\n${advice}`,
    );
  }

  if (actual !== from) {
    throw new UpgradeError(
      `cannot rebuild the ${from} baseline — the template at ${source.path} is now ${actual}, and this app carries no ${BASELINE_REL_PATH}. Merging against a re-render of ${actual} would silently drop the template's own changes.\n\n${advice}`,
    );
  }
}

/**
 * Interactively triage one orphan — a file the user edited that the
 * upgrade removed. Used only under `--prompt-on-orphans`; a cancel keeps
 * the file (the safe default).
 */
async function promptOrphan(rel: string): Promise<OrphanDecision> {
  const choice = await select({
    message: `Orphaned file — the template removed it, but you edited it: ${rel}`,
    options: [
      { value: 'keep', label: 'Keep — leave my edited copy in place' },
      { value: 'delete', label: 'Delete — remove it' },
    ],
  });
  return isCancel(choice) ? 'keep' : (choice as OrphanDecision);
}

/**
 * The plain `hex upgrade <new-template>` path.
 *
 * `cwd` is a seam for tests — the command passes `process.cwd()`.
 */
export async function runPlainUpgrade(
  templateArg: string,
  promptOnOrphans: boolean,
  cwd: string = process.cwd(),
): Promise<void> {
  const loaded = await readLockfileUpward(cwd);
  if (!loaded) {
    throw new UpgradeError(
      'no .hex/lockfile.yaml here — `hex upgrade` runs inside an app generated by `hex new`',
    );
  }
  const from = loaded.lockfile.root.version;

  const newTemplate = isAbsolute(templateArg) ? templateArg : resolve(cwd, templateArg);
  const newBundle = await loadFromPath(newTemplate);
  const to = newBundle.manifest.version;

  if (from === to) {
    console.log(brand.dim(`already at ${to} — nothing to upgrade`));
    return;
  }

  const newSource: SourceSpec = { kind: 'file', path: newTemplate };

  // `pristine_new` renders the lockfile rebased onto the newer template.
  const rebased: Lockfile = {
    ...loaded.lockfile,
    root: { ...loaded.lockfile.root, version: to, source: newSource },
  };
  const migrationsDir = join(newTemplate, '.hex', 'migrations');

  const environment: UpgradeEnvironment = {
    availableVersions: [from, to],
    pristineFor: async (version) => {
      if (version === to) return reconstructPristine(rebased);
      // The merge base is the tree Hex actually wrote at `from` — read
      // back from `.hex/pristine/`, never re-derived from a template
      // path that may since have moved on to another version.
      const baseline = await materializeBaseline(loaded.rootDir);
      if (baseline) return baseline;
      // Pre-baseline app: fall back to re-rendering the recorded source,
      // but only once we know that source still holds `from`.
      await assertSourceStillHolds(loaded.lockfile, from);
      return reconstructPristine(loaded.lockfile);
    },
    migrationsDirFor: async (toVersion) =>
      toVersion === to && existsSync(migrationsDir) ? migrationsDir : null,
  };

  const outcome = await runUpgrade({
    appRoot: cwd,
    target: to,
    environment,
    onOrphan: promptOnOrphans ? promptOrphan : undefined,
    newSource,
  });

  const m = outcome.merge;
  console.log(
    `${brand.bold(`hex upgrade ${from} → ${to}`)}  ${brand.dim(
      `(${m.added.length} added, ${m.merged.length} merged, ${m.deleted.length} deleted)`,
    )}`,
  );

  if (outcome.orphans.length > 0) {
    console.log(
      brand.warn(
        `${sym.warn()} ${outcome.orphans.length} orphaned file(s) have your edits — kept in place, review and clean up if desired:`,
      ),
    );
    for (const file of outcome.orphans) console.log(`    ${file}`);
  }

  if (outcome.userTreeChanges.length > 0) {
    console.log(
      brand.warn(
        `${sym.warn()} a user-tree migration edited your code directly — review these ${outcome.userTreeChanges.length} file(s):`,
      ),
    );
    for (const file of outcome.userTreeChanges) console.log(`    ${file}`);
  }

  if (outcome.status === 'clean') {
    console.log(brand.done(`${sym.ok()} upgrade complete — lockfile updated`));
    return;
  }

  console.error(
    brand.error(
      `${sym.err()} ${outcome.conflicts.length} file(s) have conflicts — resolve the markers, then`,
    ),
  );
  for (const file of outcome.conflicts) console.error(`    ${file}`);
  console.error(brand.dim('  run `hex upgrade --continue` when done, or `hex upgrade --abort`'));
  process.exitCode = 1;
}
