import { existsSync } from 'node:fs';
import { isAbsolute, join, resolve } from 'node:path';
import type { Command } from 'commander';
import { brand } from '../brand/colors.js';
import { type Lockfile, readLockfileUpward } from '../core/lockfile/index.js';
import { loadFromPath } from '../core/sources/file-source.js';
import { reconstructPristine } from '../core/upgrade/pristine.js';
import {
  type UpgradeEnvironment,
  UpgradeError,
  abortUpgrade,
  continueUpgrade,
  runUpgrade,
} from '../core/upgrade/run.js';

/**
 * `hex upgrade` (M11.5) — the CLI surface for the upgrade engine.
 *
 *   hex upgrade <new-template>   upgrade to the version at <new-template>
 *   hex upgrade --continue       finish a paused upgrade once conflicts are resolved
 *   hex upgrade --abort          discard a paused upgrade, rolling the tree back
 *
 * The plain form reconstructs `pristine_old` from the lockfile and
 * renders `pristine_new` from the supplied newer template, then 3-way
 * merges. A clean merge rewrites the lockfile and exits 0; a conflicting
 * one leaves marker-laden files, persists `.hex/upgrade-state.yaml`, and
 * exits non-zero.
 */
export function registerUpgrade(program: Command): void {
  program
    .command('upgrade')
    .description('upgrade a generated app to a newer template version')
    .argument('[template]', 'path to the newer version of the template')
    .option('--continue', 'resume a paused upgrade after resolving conflicts', false)
    .option('--abort', 'discard an in-progress upgrade, rolling the tree back', false)
    .action(
      async (templateArg: string | undefined, opts: { continue: boolean; abort: boolean }) => {
        try {
          if (opts.continue && opts.abort) {
            throw new UpgradeError('pass either --continue or --abort, not both');
          }
          if (opts.abort) {
            const { from, to } = await abortUpgrade(process.cwd());
            console.log(brand.done(`✓ upgrade ${from} → ${to} aborted — working tree rolled back`));
            return;
          }
          if (opts.continue) {
            const { from, to } = await continueUpgrade(process.cwd());
            console.log(brand.done(`✓ upgrade ${from} → ${to} complete`));
            return;
          }
          if (!templateArg) {
            throw new UpgradeError(
              'provide the path to the newer template, or pass --continue / --abort',
            );
          }
          await runPlainUpgrade(templateArg);
        } catch (err) {
          if (err instanceof UpgradeError) {
            console.error(brand.error(`✗ ${err.message}`));
            process.exitCode = 1;
            return;
          }
          throw err;
        }
      },
    );
}

/** The plain `hex upgrade <new-template>` path. */
async function runPlainUpgrade(templateArg: string): Promise<void> {
  const cwd = process.cwd();
  const loaded = await readLockfileUpward(cwd);
  if (!loaded) {
    throw new UpgradeError(
      'no .hex/lockfile.yaml here — `hex upgrade` runs inside an app generated by `hex new`',
    );
  }
  const from = loaded.lockfile.root.version;

  const newTemplate = isAbsolute(templateArg) ? templateArg : resolve(cwd, templateArg);
  const newBundle = await loadFromPath(newTemplate);
  const to = newBundle.manifest.version;

  if (from === to) {
    console.log(brand.dim(`already at ${to} — nothing to upgrade`));
    return;
  }

  // `pristine_new` renders the lockfile rebased onto the newer template.
  const rebased: Lockfile = {
    ...loaded.lockfile,
    root: { ...loaded.lockfile.root, version: to, source: { kind: 'file', path: newTemplate } },
  };
  const migrationsDir = join(newTemplate, '.hex', 'migrations');

  const environment: UpgradeEnvironment = {
    availableVersions: [from, to],
    pristineFor: (version) => reconstructPristine(version === to ? rebased : loaded.lockfile),
    migrationsDirFor: async (toVersion) =>
      toVersion === to && existsSync(migrationsDir) ? migrationsDir : null,
  };

  const outcome = await runUpgrade({ appRoot: cwd, target: to, environment });

  const m = outcome.merge;
  console.log(
    `${brand.bold(`hex upgrade ${from} → ${to}`)}  ${brand.dim(
      `(${m.added.length} added, ${m.merged.length} merged, ${m.deleted.length} deleted)`,
    )}`,
  );

  if (outcome.status === 'clean') {
    console.log(brand.done('✓ upgrade complete — lockfile updated'));
    return;
  }

  console.error(
    brand.error(`✗ ${outcome.conflicts.length} file(s) have conflicts — resolve the markers, then`),
  );
  for (const file of outcome.conflicts) console.error(`    ${file}`);
  console.error(brand.dim('  run `hex upgrade --continue` when done, or `hex upgrade --abort`'));
  process.exitCode = 1;
}
