import { stringify as stringifyYaml } from 'yaml';
import { parseManifestObject } from '../manifest/parse.js';
import type { HexifyParam } from './substitute.js';

/**
 * Generators for the two files hexify injects: `.hex/manifest.yaml` and
 * `.hexignore`. Both are pure text builders — the pipeline decides when
 * (and whether) they touch disk.
 */

export type ManifestSeed = {
  name: string;
  /** Optional free-form kind (e.g. `webapp`, `lib`); omitted when blank. */
  kind?: string;
  params: HexifyParam[];
};

/**
 * Build the manifest YAML for a hexified template. Every param becomes
 * a string prompt whose DEFAULT is the original concrete value — so a
 * render with all defaults reproduces the pre-hexify tree, which is
 * exactly what the round-trip gate proves.
 *
 * The object is validated through `parseManifestObject` BEFORE being
 * stringified: a generator bug fails loudly here, not later in some
 * consumer's `hex new`. No `sections:` (they must cover every prompt —
 * needless coupling for a generated file) and no `pattern:` in V1.
 */
export function buildManifestYaml(seed: ManifestSeed): string {
  const prompts = seed.params.map((p) => ({
    [p.name]: {
      type: 'string',
      default: p.value,
      description: p.description,
    },
  }));

  const manifest: Record<string, unknown> = {
    type: 'component',
    name: seed.name,
    version: '0.1.0',
  };
  const kind = seed.kind?.trim();
  if (kind) manifest.kind = kind;
  if (prompts.length > 0) manifest.prompts = prompts;

  parseManifestObject(manifest);
  return stringifyYaml(manifest);
}

/**
 * Safety floor for the generated `.hexignore`. `walkTemplate` skips
 * `.hex/` and `.hexignore` on its own but NOT `.git/` — and a hexified
 * repo renders straight from a working tree that has one. node_modules
 * and .DS_Store are the on-disk-but-not-template usual suspects. The
 * two H3 handoff working files must be excluded too: they live at the
 * repo root during the loop, and scanning them would count their own
 * proposal values as template occurrences and bake them into the
 * template (then classify "missing" in every adopt).
 */
const HEXIGNORE_DEFAULTS = [
  '.git/',
  'node_modules/',
  '.DS_Store',
  'hexify-prompt.md',
  'hexify.plan.yaml',
];

/**
 * Seed `.hexignore` from the repo's `.gitignore`: what a team keeps out
 * of git is not part of their template either, and those files ARE on
 * disk (node_modules, dist), so the render walk must skip them.
 * Comments are preserved; lines duplicating the defaults are dropped.
 */
export function buildHexignore(gitignoreText: string | undefined): string {
  const lines = [
    '# generated by hex hexify — paths the template render must skip',
    ...HEXIGNORE_DEFAULTS,
  ];
  const seen = new Set(HEXIGNORE_DEFAULTS);

  const inherited: string[] = [];
  for (const raw of (gitignoreText ?? '').split('\n')) {
    const line = raw.trimEnd();
    if (line === '') continue;
    if (!line.startsWith('#') && seen.has(line)) continue;
    if (!line.startsWith('#')) seen.add(line);
    inherited.push(line);
  }
  if (inherited.length > 0) {
    lines.push('# inherited from .gitignore', ...inherited);
  }
  return `${lines.join('\n')}\n`;
}
