import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  BASELINE_REL_PATH,
  captureBaseline,
  commitBaseline,
  discardBaseline,
  hasBaseline,
  materializeBaseline,
  stageBaseline,
} from '../../../src/core/upgrade/baseline.js';

let work: string;

beforeEach(async () => {
  work = await mkdtemp(join(tmpdir(), 'hex-baseline-test-'));
});

afterEach(async () => {
  await rm(work, { recursive: true, force: true });
});

async function writeFiles(dir: string, files: Record<string, string>): Promise<void> {
  for (const [rel, body] of Object.entries(files)) {
    const abs = join(dir, rel);
    await mkdir(join(abs, '..'), { recursive: true });
    await writeFile(abs, body, 'utf8');
  }
}

const read = (path: string): Promise<string> => readFile(path, 'utf8');

describe('pristine baseline', () => {
  it('captures the app tree, skipping .hex / .git / node_modules', async () => {
    const app = join(work, 'app');
    await writeFiles(app, {
      'README.md': '# app\n',
      'src/index.ts': 'export const x = 1;\n',
      '.hex/lockfile.yaml': 'schema_version: 1\n',
      '.git/HEAD': 'ref: refs/heads/main\n',
      'node_modules/dep/index.js': 'module.exports = {};\n',
    });

    expect(hasBaseline(app)).toBe(false);
    await captureBaseline(app);
    expect(hasBaseline(app)).toBe(true);

    const baseline = join(app, BASELINE_REL_PATH);
    expect(await read(join(baseline, 'README.md'))).toBe('# app\n');
    expect(await read(join(baseline, 'src/index.ts'))).toBe('export const x = 1;\n');
    // Hex metadata and non-artifact dirs stay out — otherwise the baseline
    // would recurse into itself and the merge would see files the template
    // never owned.
    expect(existsSync(join(baseline, '.hex'))).toBe(false);
    expect(existsSync(join(baseline, '.git'))).toBe(false);
    expect(existsSync(join(baseline, 'node_modules'))).toBe(false);
  });

  it('materializes a *copy* — the engine mutates and deletes what it is handed', async () => {
    const app = join(work, 'app');
    await writeFiles(app, { 'README.md': '# app\n' });
    await captureBaseline(app);

    const materialized = await materializeBaseline(app);
    expect(materialized).not.toBeNull();
    expect(materialized).not.toBe(join(app, BASELINE_REL_PATH));
    expect(await read(join(materialized as string, 'README.md'))).toBe('# app\n');

    // Destroying the materialized tree (as the upgrade engine does) leaves
    // the stored baseline intact.
    await rm(materialized as string, { recursive: true, force: true });
    expect(hasBaseline(app)).toBe(true);
    expect(await read(join(app, BASELINE_REL_PATH, 'README.md'))).toBe('# app\n');
  });

  it('returns null when the app has no baseline (generated by an older Hex)', async () => {
    const app = join(work, 'app');
    await writeFiles(app, { 'README.md': '# app\n' });
    expect(await materializeBaseline(app)).toBeNull();
  });

  it('commit promotes the staged tree; the old baseline is replaced', async () => {
    const app = join(work, 'app');
    await writeFiles(app, { 'README.md': 'v1\n', 'gone.txt': 'dropped by v2\n' });
    await captureBaseline(app);

    const next = join(work, 'pristine-new');
    await writeFiles(next, { 'README.md': 'v2\n' });
    await stageBaseline(app, next);

    // Staged, not yet live.
    expect(await read(join(app, BASELINE_REL_PATH, 'README.md'))).toBe('v1\n');

    await commitBaseline(app);
    expect(await read(join(app, BASELINE_REL_PATH, 'README.md'))).toBe('v2\n');
    // A file the new version no longer ships is gone from the baseline too.
    expect(existsSync(join(app, BASELINE_REL_PATH, 'gone.txt'))).toBe(false);
    expect(existsSync(join(app, '.hex', 'pristine.next'))).toBe(false);
  });

  it('discard drops the staged tree and leaves the baseline on the current version', async () => {
    const app = join(work, 'app');
    await writeFiles(app, { 'README.md': 'v1\n' });
    await captureBaseline(app);

    const next = join(work, 'pristine-new');
    await writeFiles(next, { 'README.md': 'v2\n' });
    await stageBaseline(app, next);
    await discardBaseline(app);

    expect(existsSync(join(app, '.hex', 'pristine.next'))).toBe(false);
    expect(await read(join(app, BASELINE_REL_PATH, 'README.md'))).toBe('v1\n');
  });

  it('commit is a no-op when nothing is staged', async () => {
    const app = join(work, 'app');
    await writeFiles(app, { 'README.md': 'v1\n' });
    await captureBaseline(app);
    await commitBaseline(app);
    expect(await read(join(app, BASELINE_REL_PATH, 'README.md'))).toBe('v1\n');
  });
});
